"""empty message

Revision ID: d44b3d9b5d9f
Revises: cfc475c30d55
Create Date: 2020-07-06 18:16:36.990546

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd44b3d9b5d9f'
down_revision = 'cfc475c30d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'artist_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('show', 'venue_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'venue_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('show', 'artist_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
